# Data validation and pre-processing technique

In [1]:
#import library packages
import pandas as pd
import numpy as np

In [2]:
#Load given dataset
data = pd.read_csv("diabetes.csv")

In [3]:
import warnings
warnings.filterwarnings('ignore')

Before drop the given dataset

In [4]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   
1            0       84             82             31      125  38.2   
2            0      145              0              0        0  44.2   
3            0      135             68             42      250  42.3   
4            1      139             62             41      480  40.7   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.127   47        1  
1                     0.233   23        0  
2                     0.630   31        1  
3                     0.365   24        1  
4                     0.536   21        0

In [5]:
data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0

In [6]:
# shape
data.shape

(2000, 9)

In [7]:
#size
data.size

18000

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               2000 non-null   int64  
 1   Glucose                   2000 non-null   int64  
 2   BloodPressure             2000 non-null   int64  
 3   SkinThickness             2000 non-null   int64  
 4   Insulin                   2000 non-null   int64  
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64  
 8   Outcome                   2000 non-null   int64  
dtypes: float64(2), int64(7)
memory usage: 140.8 KB


In [9]:
data.describe()

Pregnancies      Glucose  BloodPressure  SkinThickness      Insulin  \
count  2000.000000  2000.000000    2000.000000    2000.000000  2000.000000   
mean      3.703500   121.182500      69.145500      20.935000    80.254000   
std       3.306063    32.068636      19.188315      16.103243   111.180534   
min       0.000000     0.000000       0.000000       0.000000     0.000000   
25%       1.000000    99.000000      63.500000       0.000000     0.000000   
50%       3.000000   117.000000      72.000000      23.000000    40.000000   
75%       6.000000   141.000000      80.000000      32.000000   130.000000   
max      17.000000   199.000000     122.000000     110.000000   744.000000   

               BMI  DiabetesPedigreeFunction          Age      Outcome  
count  2000.000000               2000.000000  2000.000000  2000.000000  
mean     32.193000                  0.470930    33.090500     0.342000  
std       8.149901                  0.323553    11.786423     0.474498  
min       0.000000                  0.078000    21.000000     0.000000  
25%      27.375000                  0.244000    24.000000     0.000000  
50%      32.300000                  0.376000    29.000000     0.000000  
75%      36.800000                  0.624000    40.000000     1.000000  
max      80.600000                  2.420000    81.000000     1.000000

After drop the given dataset

In [10]:
# duplicated values
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1995     True
1996     True
1997     True
1998     True
1999     True
Length: 2000, dtype: bool

In [11]:
data.duplicated().sum()

1256

In [12]:
#Checkking null values
data.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0           False    False          False          False    False  False   
1           False    False          False          False    False  False   
2           False    False          False          False    False  False   
3           False    False          False          False    False  False   
4           False    False          False          False    False  False   
...           ...      ...            ...            ...      ...    ...   
1995        False    False          False          False    False  False   
1996        False    False          False          False    False  False   
1997        False    False          False          False    False  False   
1998        False    False          False          False    False  False   
1999        False    False          False          False    False  False   

      DiabetesPedigreeFunction    Age  Outcome  
0                        False  False    False  
1                        False  False    False  
2                        False  False    False  
3                        False  False    False  
4                        False  False    False  
...                        ...    ...      ...  
1995                     False  False    False  
1996                     False  False    False  
1997                     False  False    False  
1998                     False  False    False  
1999                     False  False    False  

[2000 rows x 9 columns]

In [13]:
# sum of null values
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [14]:
#drop the duplicated values
data = data.dropna()

In [15]:
# features of the dataset
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [16]:
# unique valures of individual column
data.Pregnancies.unique()

array([ 2,  0,  1,  4,  8,  3,  6,  5,  7, 10, 12,  9, 11, 13, 15, 17, 14],
      dtype=int64)

In [17]:
data.BloodPressure.unique()

array([ 62,  82,   0,  68,  78,  72,  80,  65,  90,  70,  74,  64,  60,
        50,  54,  76,  84,  92, 110,  66,  56,  88,  58,  85,  86,  75,
        48,  44, 108,  55,  96, 122,  30,  52,  98, 104,  95,  46, 102,
       100,  61,  94,  24,  38, 106, 114,  40], dtype=int64)

In [18]:
data.SkinThickness.unique()

array([ 35,  31,   0,  42,  41,  32,  17,  28,  30,  38,  18,  15,  33,
        19,  25,  39,  26,  23,  37,  47,  24,  27,  11,  21,  34,  10,
        60,  13,  20,  22,  29,  54,  40,  51,  56,  36,  14,  50,  44,
        12,  46,  16,   7,  52,  43,  45,  48,   8,  49,  63,  99,  59,
       110], dtype=int64)

In [19]:
data.BMI.unique()

array([33.6, 38.2, 44.2, 42.3, 40.7, 46.5, 25.6, 26.1, 36.8, 33.5, 32.8,
       28.9,  0. , 26.6, 26. , 30.1, 25.1, 29.3, 25.2, 37.2, 39. , 33.3,
       37.3, 36.5, 28.6, 30.4, 25. , 29.7, 22.1, 24.2, 27.3, 31.6, 27.6,
       24. , 33.2, 32.9, 37.1, 34. , 40.2, 22.7, 45.4, 27.4, 42. , 28. ,
       39.1, 19.4, 24.4, 33.7, 34.7, 23. , 37.7, 46.8, 40.5, 41.5, 25.4,
       29. , 32.5, 42.7, 19.6, 43.4, 35.1, 32. , 24.7, 32.6, 43.2, 22.4,
       24.6, 48.8, 32.4, 36.6, 38.5, 26.5, 19.1, 46.7, 23.8, 33.9, 20.4,
       28.7, 49.7, 22.5, 39.6, 29.5, 34.3, 37.4, 31.2, 30.5, 28.2, 23.2,
       53.2, 34.2, 26.8, 55. , 42.9, 34.5, 27.9, 38.3, 21.1, 33.8, 30.8,
       36.9, 39.5, 21.9, 40.6, 47.9, 50. , 40.9, 29.9, 29.6, 31.9, 28.4,
       35.4, 43.5, 32.7, 67.1, 45. , 34.9, 27.7, 35.9, 22.6, 33.1, 52.3,
       39.4, 24.3, 22.9, 34.8, 30.9, 31. , 40.1, 23.9, 37.5, 35.5, 42.8,
       42.6, 41.8, 35.8, 30. , 37.8, 34.6, 28.8, 23.6, 35.7, 36.7, 45.2,
       44. , 46.2, 35. , 43.6, 44.1, 18.4, 29.2, 27

In [20]:
data.Age.unique()

array([47, 23, 31, 24, 21, 58, 28, 67, 42, 33, 45, 22, 66, 30, 25, 55, 39,
       41, 40, 38, 35, 64, 46, 27, 56, 26, 37, 48, 54, 29, 44, 36, 32, 43,
       34, 60, 61, 69, 62, 65, 57, 52, 51, 49, 63, 59, 72, 81, 50, 53, 70,
       68], dtype=int64)

In [21]:
data.Outcome.unique()

array([1, 0], dtype=int64)

In [22]:
#no of not affected peoples
data[data["Outcome"] == 0 ]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1               0       84             82             31      125  38.2   
4               1      139             62             41      480  40.7   
5               0      173             78             32      265  46.5   
6               4       99             72             17        0  25.6   
7               8      194             80              0        0  26.1   
...           ...      ...            ...            ...      ...   ...   
1993            2       87              0             23        0  28.9   
1994            1       79             60             42       48  43.5   
1995            2       75             64             24       55  29.7   
1997            6       85             78              0        0  31.2   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
1                        0.233   23        0  
4                        0.536   21        0  
5                        1.159   58        0  
6                        0.294   28        0  
7                        0.551   67        0  
...                        ...  ...      ...  
1993                     0.773   25        0  
1994                     0.678   23        0  
1995                     0.370   33        0  
1997                     0.382   42        0  
1999                     0.547   25        0  

[1316 rows x 9 columns]

In [23]:
#number of not affected peoples
data[data["Outcome"] == 0 ].shape

(1316, 9)

In [24]:
#number of not affected peoples
data[data["Outcome"] == 1 ].shape

(684, 9)

In [25]:
# Age details
print("Maximum Age :",data["Age"].max())
print("Minimum Age :",data["Age"].min())
print("Mean of Age :","%.2f" %   data["Age"].mean())

Maximum Age : 81
Minimum Age : 21
Mean of Age : 33.09


In [26]:
# BMI  details
print("Maximum BMI :",data["BMI"].max())
print("Minimum BMI :",data["BMI"].min())
print("Mean of BMI :","%.2f" % data["BMI"].mean())

Maximum BMI : 80.6
Minimum BMI : 0.0
Mean of BMI : 32.19


In [27]:
# BMI  details
print("Maximum BloodPressure :",data["BloodPressure"].max())
print("Minimum BloodPressure :",data["BloodPressure"].min())
print("Mean of BloodPressure :","%.2f" % data["BloodPressure"].mean())

Maximum BloodPressure : 122
Minimum BloodPressure : 0
Mean of BloodPressure : 69.15


In [28]:
# Glucose  details
print("Maximum Glucose :",data["Glucose"].max())
print("Minimum Glucose :",data["Glucose"].min())
print("Mean of Glucose :","%.2f" % data["Glucose"].mean())

Maximum Glucose : 199
Minimum Glucose : 0
Mean of Glucose : 121.18


In [29]:
pd.Categorical(data["Pregnancies"]).describe()

counts   freqs
categories                
0              301  0.1505
1              356  0.1780
2              284  0.1420
3              195  0.0975
4              191  0.0955
5              141  0.0705
6              131  0.0655
7              100  0.0500
8               96  0.0480
9               70  0.0350
10              54  0.0270
11              24  0.0120
12              23  0.0115
13              22  0.0110
14               7  0.0035
15               2  0.0010
17               3  0.0015

In [30]:
data.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.120405       0.149672      -0.063375   
Glucose                      0.120405  1.000000       0.138044       0.062368   
BloodPressure                0.149672  0.138044       1.000000       0.198800   
SkinThickness               -0.063375  0.062368       0.198800       1.000000   
Insulin                     -0.076600  0.320371       0.087384       0.448859   
BMI                          0.019475  0.226864       0.281545       0.393760   
DiabetesPedigreeFunction    -0.025453  0.123243       0.051331       0.178299   
Age                          0.539457  0.254496       0.238375      -0.111034   
Outcome                      0.224437  0.458421       0.075958       0.076040   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.076600  0.019475                 -0.025453   
Glucose                   0.320371  0.226864                  0.123243   
BloodPressure             0.087384  0.281545                  0.051331   
SkinThickness             0.448859  0.393760                  0.178299   
Insulin                   1.000000  0.223012                  0.192719   
BMI                       0.223012  1.000000                  0.125719   
DiabetesPedigreeFunction  0.192719  0.125719                  1.000000   
Age                      -0.085879  0.038987                  0.026569   
Outcome                   0.120924  0.276726                  0.155459   

                               Age   Outcome  
Pregnancies               0.539457  0.224437  
Glucose                   0.254496  0.458421  
BloodPressure             0.238375  0.075958  
SkinThickness            -0.111034  0.076040  
Insulin                  -0.085879  0.120924  
BMI                       0.038987  0.276726  
DiabetesPedigreeFunction  0.026569  0.155459  
Age                       1.000000  0.236509  
Outcome                   0.236509  1.000000

In [31]:
df=data.corr()
df["Age"].sort_values(ascending=False)

Age                         1.000000
Pregnancies                 0.539457
Glucose                     0.254496
BloodPressure               0.238375
Outcome                     0.236509
BMI                         0.038987
DiabetesPedigreeFunction    0.026569
Insulin                    -0.085879
SkinThickness              -0.111034
Name: Age, dtype: float64

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [33]:
var_mod = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

for i in var_mod:
    data[i] = le.fit_transform(data[i].astype(int))

In [34]:
df.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin  \
Pregnancies       1.000000  0.120405       0.149672      -0.063375 -0.076600   
Glucose           0.120405  1.000000       0.138044       0.062368  0.320371   
BloodPressure     0.149672  0.138044       1.000000       0.198800  0.087384   
SkinThickness    -0.063375  0.062368       0.198800       1.000000  0.448859   
Insulin          -0.076600  0.320371       0.087384       0.448859  1.000000   

                    BMI  DiabetesPedigreeFunction       Age   Outcome  
Pregnancies    0.019475                 -0.025453  0.539457  0.224437  
Glucose        0.226864                  0.123243  0.254496  0.458421  
BloodPressure  0.281545                  0.051331  0.238375  0.075958  
SkinThickness  0.393760                  0.178299 -0.111034  0.076040  
Insulin        0.223012                  0.192719 -0.085879  0.120924

# removing outliers in the dataset

In [35]:
#checking the columns with outliers
for feature in data:
    Q1 = data[feature].quantile(0.25)
    Q3 = data[feature].quantile(0.75)
    IQR = Q3-Q1
    lower = Q1- 1.5*IQR
    upper = Q3 + 1.5*IQR
    
    if data[(data[feature] > upper)].any(axis=None):
        print(feature,"yes")
    else:
        print(feature, "no")

Pregnancies yes
Glucose no
BloodPressure yes
SkinThickness no
Insulin no
BMI yes
DiabetesPedigreeFunction yes
Age yes
Outcome no


In [41]:
# We determine outliers between all variables with the LOF method
from sklearn.neighbors import LocalOutlierFactor
lof =LocalOutlierFactor(n_neighbors= 10)
lof.fit_predict(data)

array([1, 1, 1, ..., 1, 1, 1])

In [42]:
df_scores = lof.negative_outlier_factor_
np.sort(df_scores)[0:30]

array([-1.96289841, -1.96289841, -1.92783259, -1.92783259, -1.92783259,
       -1.83245274, -1.83245274, -1.76573083, -1.76573083, -1.76573083,
       -1.75349326, -1.75349326, -1.75349326, -1.72696072, -1.72696072,
       -1.70391588, -1.70391588, -1.70391588, -1.64860046, -1.64860046,
       -1.64860046, -1.64697687, -1.64697687, -1.64078096, -1.64078096,
       -1.62155097, -1.62155097, -1.57955436, -1.57955436, -1.57955436])

In [43]:
#We choose the threshold value according to lof scores
threshold = np.sort(df_scores)[7]
threshold

-1.7657308320434972

In [45]:
#We delete those that are higher than the threshold
outlier = df_scores > threshold
data = data[outlier]

In [47]:
# The size of the data set was examined.
data.shape

(1990, 9)